"""empty message

Revision ID: b3ce6ea9a141
Revises: a995bbe3fdf0
Create Date: 2016-11-08 23:45:08.599578

"""

# revision identifiers, used by Alembic.
revision = 'b3ce6ea9a141'
down_revision = 'a995bbe3fdf0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cat')
    ### end Alembic commands ###
